services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    volumes:
      - mongodb-data:/data/db

  redis:
    image: 'redis:latest'
    command: redis-server --requirepass secret
    ports:
      - '6379'
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data: